# Generated by Django 5.1.4 on 2024-12-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_experience_job_published_at_job_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(default=1),
        ),
    ]
