# Generated by Django 5.1.4 on 2024-12-14 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_vacancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='vacancy',
            new_name='Vacancy',
        ),
    ]
