# Generated by Django 5.1.4 on 2024-12-14 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_rename_vacancy_job_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='Vacancy',
        ),
    ]
